### PR TITLE
Refactoring/UI

### PR DESCRIPTION
**Pull request by Zadvornyi**
Big refactoring:

- split all views in separate folders
- split all callbacks in separate folders
- update gui_run.sh
- update kill.sh

### CODE REVIEW

**Comment by krakenrf** [comment]
Tested and appears to have no regressions. @godsic any comments?

**Comment by godsic** [comment]
@krakenrf have not tested yet, but it’s on my list for today.

**Comment by Zadvornyi** [comment]
I have resolved conflict

**Comment by godsic** [comment]
@krakenrf Have not found regressions. Seems OK to merge (I would suggest to "Squash" it all in one commit).

**Pull request merged**
