### PR TITLE
Refactoring SDR sources

### PR DESCRIPTION
**Pull request by redradist**

### CODE REVIEW

**Comment by godsic** [comment]
@redradist I think you forgot to update imports.

**Comment by redradist** [comment]
> @redradist I think you forgot to update imports.

@godsic Fixed

**Comment by krakenrf** [comment]
Got some conflicts after the last merges, can you please check?

**Comment by godsic** [comment]
@redradist Please fix the merge conflict.

**Comment by redradist** [comment]
> @redradist Please fix the merge conflict.

@godsic @krakenrf Done

**Comment by krakenrf** [comment]
@redradist got some problems with this one, it seems some paths haven't been updated

```
.       .CRITICAL:shmemIface:OS error: [Errno 2] No such file or directory: '/home/krakenrf/krakensdr_doa/krakensdr_doa/heimdall_daq_fw/Firmware/_data_control/fw_delay_sync_iq'
CRITICAL:shmemIface:Failed to open control fifos
CRITICAL:kraken_sdr_receiver:Shared memory initialization failed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/krakenrf/miniforge3/envs/kraken/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_signal_processing/kraken_sdr_signal_processor.py", line 302, in run
    if self.module_receiver.get_iq_online():
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/kraken_sdr_receiver.py", line 192, in get_iq_online
    active_buff_index = self.in_shmem_iface.wait_buff_free()
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/shmemIface.py", line 196, in wait_buff_free
    signal = unpack("B", os.read(self.fw_ctr_fifo, 1))[0]
TypeError: an integer is required (got type NoneType)
```

**Comment by redradist** [comment]
> @redradist got some problems with this one, it seems some paths haven't been updated
> 
> ```
> .       .CRITICAL:shmemIface:OS error: [Errno 2] No such file or directory: '/home/krakenrf/krakensdr_doa/krakensdr_doa/heimdall_daq_fw/Firmware/_data_control/fw_delay_sync_iq'
> CRITICAL:shmemIface:Failed to open control fifos
> CRITICAL:kraken_sdr_receiver:Shared memory initialization failed
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/home/krakenrf/miniforge3/envs/kraken/lib/python3.9/threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_signal_processing/kraken_sdr_signal_processor.py", line 302, in run
>     if self.module_receiver.get_iq_online():
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/kraken_sdr_receiver.py", line 192, in get_iq_online
>     active_buff_index = self.in_shmem_iface.wait_buff_free()
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/shmemIface.py", line 196, in wait_buff_free
>     signal = unpack("B", os.read(self.fw_ctr_fifo, 1))[0]
> TypeError: an integer is required (got type NoneType)
> ```

@krakenrf Fixed the issue by applying changes also for relative paths in kraken_sdr_receiver.py file

**Pull request merged**
