### PR TITLE
Update DAQ status even if no data from receiver

### PR DESCRIPTION
**Pull request by godsic**
It turns out that the `get_iq_online()` call is blocking. As a result, status updates, both in GUI and `status.json`, are imposible if no frames being received from heimdall, e.g., due to USB or power failures. So lets "unblock" the call by instead reading with timeout (5s currently) Also refactor status updates to be explicit about potential failures.

### CODE REVIEW

**Comment by krakenrf** [comment]
Having an issue getting it to start with these changes. This is the log error.

Does shmemIface in heimdall need to be updated with the changes too?

> Traceback (most recent call last):
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_ui/_web_interface/app.py", line 22, in <module>
>     from maindash import app
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_ui/_web_interface/maindash.py", line 21, in <module>
>     web_interface = WebInterface()
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_ui/_web_interface/kraken_web_interface.py", line 61, in __init__
>     self.module_receiver = ReceiverRTLSDR(
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/kraken_sdr_receiver.py", line 81, in __init__
>     self.init_data_iface()
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/kraken_sdr_receiver.py", line 97, in init_data_iface
>     self.in_shmem_iface = inShmemIface(
>   File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/shmemIface.py", line 163, in __init__
>     if unpack("B", os.read(self.fw_ctr_fifo, 1))[0] == INIT_READY:
> BlockingIOError: [Errno 11] Resource temporarily unavailable

**Comment by krakenrf** [comment]
Yeah copied shmemIface to heimdall and it works now. Can you make the corresponding PR for shmemiface on heimdall too?

But also I'm now seeing an odd problem where the update rate appears to spike from ~120 ms average, to 900ms - 1.4s and it seems to skip a few frames on the UI update. It does this every few seconds. 

Spectrum update and DOA update is also stopping/lagging during those spikes, then rapidly updating shortly after the stop.

Not sure if this is just a UI update lag, or something else.

**Comment by krakenrf** [comment]
Watch the update in this recording. Whenever is lags there the spectrum and DOA update also lag.

https://github.com/krakenrf/krakensdr_doa/assets/78108016/c92d2e54-a98b-4c02-99a5-9c7bbfb42749

**Comment by krakenrf** [comment]
Actually, never mind anything about the lag spikes. It appears to do this on the original code too. Not sure why I never noticed that. So I think this is fine to merge as long as the corresponding heimdall PR is made.

**Comment by godsic** [comment]
@krakenrf good to hear, because I cannot really reproduce spikes on my side.

 I would speculate they are related to the hiccups in data transfers that might be more apparent now when I poll with timeout in a number of attempts and sleeping for 10 ms in between them. That’s where Python can potentially  execute other parts of the code.

 Regarding changes in heimdall, I can make a PR to bring implementation in-sync, but it must work anyway (I have not touched Heimdall on my side).

**Comment by krakenrf** [comment]
> Regarding changes in heimdall, I can make a PR to bring implementation in-sync, but it must work anyway (I have not touched Heimdall on my side).

Very strange, I could not get this change to work at all without updating it on heimdall too.

**Comment by godsic** [comment]
@krakenrf Very strange indeed. The behavior on the heimdall side should be virtually unchanged irrespective of my changes, as polling timeout is not engaged. The IQHeader changes are not breaking compatibility neither. I wonder if that’s some sort of timing issue🤔

**Comment by krakenrf** [comment]
I don't think it was moving the shmemIface to heimdall that fixed anything. I'm just getting random problems with the PR, sometimes it starts, most of the time not.

ui.log:

```
gpsd Available
Traceback (most recent call last):
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_ui/_web_interface/app.py", line 22, in <module>
    from maindash import app
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_ui/_web_interface/maindash.py", line 21, in <mo>
    web_interface = WebInterface()
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_ui/_web_interface/kraken_web_interface.py", lin>
    self.module_receiver = ReceiverRTLSDR(
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/kraken_sdr_receiver.py", line 81,>
    self.init_data_iface()
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/kraken_sdr_receiver.py", line 97,>
    self.in_shmem_iface = inShmemIface(
  File "/home/krakenrf/krakensdr_doa/krakensdr_doa/_sdr/_receiver/shmemIface.py", line 163, in __in>
    if unpack("B", os.read(self.fw_ctr_fifo, 1))[0] == INIT_READY:
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

delay_sync.log shows:

```
INFO:__main__:IQ adjustment vector: abs:[1. 1. 1. 1. 1.]
INFO:__main__:IQ adjustment vector: phase:[0. 0. 0. 0. 0.]
WARNING:shmemIface:Shared memory not exist: [Errno 2] No such file or directory: '/delay_sync_iq_A'
WARNING:shmemIface:Shared memory not exist: [Errno 2] No such file or directory: '/delay_sync_iq_B'
WARNING:shmemIface:Shared memory not exist: [Errno 2] No such file or directory: '/delay_sync_hwc_A'
WARNING:shmemIface:Shared memory not exist: [Errno 2] No such file or directory: '/delay_sync_hwc_B'
WARNING:shmemIface:Dropping frame.. Total: [1]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [2]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [1]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [3]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [4]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [5]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [6]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [7]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [8]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [9]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
WARNING:shmemIface:Dropping frame.. Total: [10]
WARNING:shmemIface:Due to: [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/krakenrf/krakensdr_doa/heimdall_daq_fw/Firmware/_daq_core/delay_sync.py", line 820, i>
    delay_synchronizer_inst0.start()
  File "/home/krakenrf/krakensdr_doa/heimdall_daq_fw/Firmware/_daq_core/delay_sync.py", line 461, i>
    active_buffer_index_iq = self.out_shmem_iface_iq.wait_buff_free()
  File "/home/krakenrf/krakensdr_doa/heimdall_daq_fw/Firmware/_daq_core/shmemIface.py", line 123, i>
    signal = unpack("B", buffer)[0]
struct.error: unpack requires a buffer of 1 bytes
/home/krakenrf/miniforge3/envs/kraken/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWa>
  warnings.warn('resource_tracker: There appear to be %d '
```

hwc.log:

```
Traceback (most recent call last):
  File "/home/krakenrf/krakensdr_doa/heimdall_daq_fw/Firmware/_daq_core/hw_controller.py", line 702>
    HWC_inst0.start()
  File "/home/krakenrf/krakensdr_doa/heimdall_daq_fw/Firmware/_daq_core/hw_controller.py", line 415>
    active_buff_index = self.in_shmem_iface.wait_buff_free()
  File "/home/krakenrf/krakensdr_doa/heimdall_daq_fw/Firmware/_daq_core/shmemIface.py", line 197, i>
    signal = unpack("B", os.read(self.fw_ctr_fifo, 1))[0]
struct.error: unpack requires a buffer of 1 bytes
```

**Comment by godsic** [comment]
@krakenrf Could you please try with my recent changes? Before that, please also revert heimdall to master to discard any changes to `shmemIface` there.

**Comment by krakenrf** [comment]
@godsic working perfectly now thanks. will merge

**Pull request merged**
