### PR TITLE
Add root-MUSIC DoA estimation method

### PR DESCRIPTION
**Pull request by godsic**
As suggested by A. Barabell, "Improving the resolution performance of eigenstructure-based direction-finding algorithms." ICASSP'83. IEEE International Conference on Acoustics, Speech, and Signal Processing. Vol. 8. IEEE, 1983.
doi: 10.1109/ICASSP.1983.1172124

Works universally for ULA and UCA. For UCA, the PME transformation is automatically applied to input signal in order to get correlation matrix with Vandermonde structure.

Root-MUSIC might provide better performance for low SNRs conditions and, theoretically, less sensitive to amplitude variations across the channels.

### CODE REVIEW

**Comment by krakenrf** [comment]
Thanks the main part seems to work well.

One bug: When root-music is selected it's no longer possible to change the "expected number of RF sources". But if I select MUSIC, then change it, and then change back to root-music it works.

Also, for this to work with the standard Android app method it seems the array of 360 outputs will need to be more than a single non-zero value, it needs to look like a lobe. Can we add an option to artificially fatten up the output to a resolution of say 5 degrees (or maybe user tunable, or maybe based on the Rayleigh resolution divided by 10 at the current spacing multiplier)?

e.g. if the output is 80 at 15 degrees, we should artificially add values like 20, 40, 80, 40, 20 at 13, 14, 15, 16, 17 degrees. Not sure what sort of curve scaling would work best though and how to handle two peaks close to another.

**Comment by godsic** [comment]
@krakenrf Fixed the bug now, thanks for trying! Yes, at the moment shape of the lobe is artificial and non-representative of actual resolution. The problem is that for MUSIC its not that simple as Rayleigh resolution divided  by some factor.  It very much depends on SNR and CPI length, see, for instance, Eq. 30a in https://www.ee.columbia.edu/~dpwe/papers/RaoH1989-rootmus.pdf . There are also other closed form expressions for MUSIC RMSE. I am still doing the literature search to figure out those for ULA and UCA cases (need to ping people around with relevant journal subscriptions at times). Finally, I need to figure out the shape of the lobe. Intuition suggests Lorentzian one, but, again, some literature search needs to be done to get it right.

**Comment by krakenrf** [comment]
Interesting, didn't realize the lobe shape was that complex.

I think for now it's fine to base the lobe shape on rayleigh res/10 with halving power every +-1 deg, then at least I can merge this and it will work with the app for initial field testing. The lobe shape can be refined later, but I'm not convinced the actual shape will have a big practical effect on the app anyway.

**Comment by godsic** [comment]
@rakenrf Fixed the shape of the lobe for root-music. It is approximated by multimodal Gaussian.
 
The current limitations are:

- the standard deviation is fixed to 1 degree, i.e., FWHM is 2.36 deg;
- if more than one lobe is present, then all of them will have the same amplitude, irrespective of the corresponding SNRs or correlation matrix eigen-values, etc.

So it should be mergeable now, but further research is needed to remove the aforementioned limitations.

**Comment by godsic** [comment]
@krakenrf Taking into account `array_offset` now.

**Pull request merged**
